// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package checkout is a generated GoMock package.
package checkout

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/jekiapp/hi-mod-arch/internal/model"
)

// MockrenderPageInterface is a mock of renderPageInterface interface.
type MockrenderPageInterface struct {
	ctrl     *gomock.Controller
	recorder *MockrenderPageInterfaceMockRecorder
}

// MockrenderPageInterfaceMockRecorder is the mock recorder for MockrenderPageInterface.
type MockrenderPageInterfaceMockRecorder struct {
	mock *MockrenderPageInterface
}

// NewMockrenderPageInterface creates a new mock instance.
func NewMockrenderPageInterface(ctrl *gomock.Controller) *MockrenderPageInterface {
	mock := &MockrenderPageInterface{ctrl: ctrl}
	mock.recorder = &MockrenderPageInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockrenderPageInterface) EXPECT() *MockrenderPageInterfaceMockRecorder {
	return m.recorder
}

// GetCartFromDB mocks base method.
func (m *MockrenderPageInterface) GetCartFromDB(userID int64) (model.CartData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCartFromDB", userID)
	ret0, _ := ret[0].(model.CartData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCartFromDB indicates an expected call of GetCartFromDB.
func (mr *MockrenderPageInterfaceMockRecorder) GetCartFromDB(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCartFromDB", reflect.TypeOf((*MockrenderPageInterface)(nil).GetCartFromDB), userID)
}

// GetProductData mocks base method.
func (m *MockrenderPageInterface) GetProductData(productID int64) (model.ProductData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductData", productID)
	ret0, _ := ret[0].(model.ProductData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductData indicates an expected call of GetProductData.
func (mr *MockrenderPageInterfaceMockRecorder) GetProductData(productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductData", reflect.TypeOf((*MockrenderPageInterface)(nil).GetProductData), productID)
}

// GetPromotion mocks base method.
func (m *MockrenderPageInterface) GetPromotion(coupon string, totalPrice float64) (model.PromotionData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPromotion", coupon, totalPrice)
	ret0, _ := ret[0].(model.PromotionData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPromotion indicates an expected call of GetPromotion.
func (mr *MockrenderPageInterfaceMockRecorder) GetPromotion(coupon, totalPrice interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPromotion", reflect.TypeOf((*MockrenderPageInterface)(nil).GetPromotion), coupon, totalPrice)
}

// GetUserInfo mocks base method.
func (m *MockrenderPageInterface) GetUserInfo(userID int64) (model.UserData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserInfo", userID)
	ret0, _ := ret[0].(model.UserData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserInfo indicates an expected call of GetUserInfo.
func (mr *MockrenderPageInterfaceMockRecorder) GetUserInfo(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserInfo", reflect.TypeOf((*MockrenderPageInterface)(nil).GetUserInfo), userID)
}
