// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package checkout is a generated GoMock package.
package checkout

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/jekiapp/hi-mod-arch/internal/model"
)

// MockIRenderPage is a mock of IRenderPage interface.
type MockIRenderPage struct {
	ctrl     *gomock.Controller
	recorder *MockIRenderPageMockRecorder
}

// MockIRenderPageMockRecorder is the mock recorder for MockIRenderPage.
type MockIRenderPageMockRecorder struct {
	mock *MockIRenderPage
}

// NewMockIRenderPage creates a new mock instance.
func NewMockIRenderPage(ctrl *gomock.Controller) *MockIRenderPage {
	mock := &MockIRenderPage{ctrl: ctrl}
	mock.recorder = &MockIRenderPageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRenderPage) EXPECT() *MockIRenderPageMockRecorder {
	return m.recorder
}

// GetCartFromDB mocks base method.
func (m *MockIRenderPage) GetCartFromDB(userID int64) (model.CartData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCartFromDB", userID)
	ret0, _ := ret[0].(model.CartData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCartFromDB indicates an expected call of GetCartFromDB.
func (mr *MockIRenderPageMockRecorder) GetCartFromDB(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCartFromDB", reflect.TypeOf((*MockIRenderPage)(nil).GetCartFromDB), userID)
}

// GetProductData mocks base method.
func (m *MockIRenderPage) GetProductData(productID int64) (model.ProductData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductData", productID)
	ret0, _ := ret[0].(model.ProductData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductData indicates an expected call of GetProductData.
func (mr *MockIRenderPageMockRecorder) GetProductData(productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductData", reflect.TypeOf((*MockIRenderPage)(nil).GetProductData), productID)
}

// GetPromotion mocks base method.
func (m *MockIRenderPage) GetPromotion(coupon string, totalPrice float64) (model.PromotionData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPromotion", coupon, totalPrice)
	ret0, _ := ret[0].(model.PromotionData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPromotion indicates an expected call of GetPromotion.
func (mr *MockIRenderPageMockRecorder) GetPromotion(coupon, totalPrice interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPromotion", reflect.TypeOf((*MockIRenderPage)(nil).GetPromotion), coupon, totalPrice)
}

// GetUserInfo mocks base method.
func (m *MockIRenderPage) GetUserInfo(userID int64) (model.UserData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserInfo", userID)
	ret0, _ := ret[0].(model.UserData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserInfo indicates an expected call of GetUserInfo.
func (mr *MockIRenderPageMockRecorder) GetUserInfo(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserInfo", reflect.TypeOf((*MockIRenderPage)(nil).GetUserInfo), userID)
}
